# Generated by Django 5.2.1 on 2025-05-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
