# Generated by Django 5.2.1 on 2025-05-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffApp', '0003_staffprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffApp.department'),
        ),
    ]
