# Generated by Django 5.2.1 on 2025-05-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffApp', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
