# Generated by Django 5.2.1 on 2025-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffApp', '0006_staffprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
